# syntax=docker.io/docker/dockerfile:1

FROM node:22-alpine

# Check https://github.com/nodejs/docker-node/tree/main#nodealpine to understand why libc6-compat might be needed
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Copy the Prisma schema first
COPY prisma ./prisma

# Install dependencies
COPY package.json package-lock.json* yarn.lock* pnpm-lock.yaml* .npmrc* ./
RUN \
  if [ -f yarn.lock ]; then yarn; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
  else echo "Lockfile not found." && exit 1; \
  fi

# Install sharp for image optimization even in dev
RUN npm install --no-package-lock sharp

# Copy rest of the source code
COPY . .

# Set development environment
ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1

# Expose port
EXPOSE 3000

# Start development server
CMD ["npm", "run", "dev"] 